global using BuildingBlocks.CQRS;
global using BuildingBlocks.Exceptions;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Microstore.Service.OrderingApplication.Data;
global using Microstore.Service.OrderingApplication.Dtos;
global using Microstore.Service.OrderingApplication.Exceptions;
global using Microstore.Service.OrderingDomain.Models;
global using Microstore.Service.OrderingDomain.ValueObjects;
