services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  catalogapi:
    image: ${DOCKER_REGISTRY-}microstoreservicescatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Microstore.Services.CatalogApi/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}microstoreservicebasketapi
    build:
      context: .
      dockerfile: Services/Basket/Microstore.Service.BasketApi/Dockerfile
      
  discountgrpc:
    image: ${DOCKER_REGISTRY-}microstoreservicediscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Microstore.Service.DiscountGrpc/Dockerfile

  microstore.service.ordering:
    image: ${DOCKER_REGISTRY-}microstoreserviceordering
    build:
      context: .
      dockerfile: Services/Ordering/Microstore.Service.Ordering/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

