services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  microstore.services.catalogapi:
    image: ${DOCKER_REGISTRY-}microstoreservicescatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Microstore.Services.CatalogApi/Dockerfile

  microstore.service.basketapi:
    image: ${DOCKER_REGISTRY-}microstoreservicebasketapi
    build:
      context: .
      dockerfile: services/Basket/Microstore.Service.BasketApi/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
