services:
  catalogdb:
    image: postgres

  microstore.services.catalogapi:
    image: ${DOCKER_REGISTRY-}microstoreservicescatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Microstore.Services.CatalogApi/Dockerfile

volumes:
  postgres_catalog:
    
