# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /home/runner/work/microstore/microstore

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Check path
      run: | 
          pwd
          ls -l
    - name: Restore dependencies
      run: dotnet restore src/microstore.sln
    - name: Build
      run: dotnet build --no-restore src/microstore.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/microstore.sln
